title: My Work
description: >- # this means to ignore newlines until "baseurl:"
  This is a section where I will keep posting my most recent contributions to science
baseurl: '/MyWork'

github_username: alexandremercieraubin
url: 'https://alexandremercieraubin.com'

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
