remote_theme: mmistakes/so-simple-theme

locale: en-US
title: "Work"
subtitle: "" 
description: ""
baseurl: "/Work"
github_username: alexandremercieraubin
url: 'https://alexandremercieraubin.com'
#logo: "/images/logo.jpg"
date_format: "%B %-d, %Y"
#read_time: true
#words_per_minute: 200
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "none" # 'ams' automatically label math equations
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-2011187-2"
disqus:
  shortname: "sosimpletheme"
twitter:
  username: "Zero"
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
kramdown: 
  math_engine: mathjax
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/
pagination:
  # ...
  sort_field: "stickiness"
  sort_reverse: false
  
# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

stickyposts:
  enabled: true   # Enable StickyPosts; default: true
  debug: true       # Show additional info; default: false
  sort: "blah"      # Optional sort field; default: "date", use "none" to avoid sorting
  reverse: true     # Ascending order, default: false
  retain: true      # Also show sticky posts in their original positions; default: false
  reverse_sticky: true    # Reverse the order of the sticky posts, e.g. oldest first; default: false

  #collection: articles   # The collection to "stickify"; default "posts"

  # Or multiple collections:
  collections:
  - posts

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  cheatsheets:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Alexandre Mercier-Aubin
  # picture: /images/something.jpg
  twitter: AlexMercierA
  # more icons can be found here: https://fontawesome.com/icons?d=gallery&p=2
  links:
    - title: Twitter
      url: https://twitter.com/AlexMercierA
      icon: fab fa-twitter-square
    - title: Website
      url: https://alexandremercieraubin.com
      icon: fab fa-vcard
    - title: GitHub
      url: https://github.com/alexandremercieraubin
      icon: fab fa-github-square


# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/AlexMercierA
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/alexandremercieraubin
    icon: fab fa-github-square
