title: My Work

github_username: alexandremercieraubin
url: 'https://alexandremercieraubin.com'

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed