title: Work
description: >- # this means to ignore newlines until "baseurl:"
  Section to list contributions
baseurl: "/MyWork/"

github_username: alexandremercieraubin
url: 'https://alexandremercieraubin.com'

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
  
header_pages:
  - about.md
footer_pages:
  - about.md